### ISSUE TITLE
Wrong namespace in "Introducing the Blog Module"

### ISSUE THREAD

**Issue by WinterSilence** [zendframework/tutorials#109]
> `<h1>Blog\ListController::indexAction()</h1>`

>  template page with Blog\ListController::indexAction() as the header

Missing directory `Controller`: `Blog\Controller\ListController::indexAction`.
Also i dont understand why classes use postfix  `Controller`? Does using `Blog\Controller\List` add any problems? 

[/tutorials/in-depth-guide/first-module/](https://docs.zendframework.com/tutorials/in-depth-guide/first-module/)

**Comment by michalbundyra** [comment]
@WinterSilence 

> Also i dont understand why classes use postfix Controller? Does using Blog\Controller\List add any problems?

Yes. `list` is restricted word in PHP so you cannot define class with name `List`.
See:
- https://www.php.net/manual/en/reserved.keywords.php
- https://3v4l.org/gfJ5Z

**Comment by WinterSilence** [comment]
@webimpress bad example for question :) Ok,  take other controller: `AlbumController` in [first tutorial](https://docs.zendframework.com/tutorials/getting-started/routing-and-controllers/) too have postfix. It's no more readable or useful. What is postfix for?

**Comment by froschdesign** [comment]
@WinterSilence 
>  It's no more readable or useful.

The choice is yours: it's a framework, and you can choose the option that you prefer and that works for you.

One option is to create an alias:
```php
use Album\Model\Album;
use Album\Controller\Album as AlbumController;

$model = new Album();
$controller = new AlbumController();
```
Or import the namespace:
```php
use Album\Model\Album;
use Album\Controller;

$model = new Album();
$controller = new Controller\Album();
```
Or use a postifx:
```php
use Album\Model\Album;
use Album\Controller\AlbumController;

$model = new Album();
$controller = new AlbumController();
```

**Comment by WinterSilence** [comment]
@froschdesign 

> The choice is yours: it's a framework, and you can choose the option that you prefer and that works for you.

yes, but i cant find other cases in tutorials + I recently started learning ZF. I don't know what problems may arise in other cases. maybe its alias for extending in application/other modules :)

**Comment by WinterSilence** [comment]
@froschdesign example for [maybe its alias for extending in application/other modules](https://koseven.ga/documentation/kohana/files).

**Comment by weierophinney** [comment]
@WinterSilence —

We tend to use suffixes within the examples for several reasons:

- When referring to the class later in the example, you can immediately grasp its context (controller, versus validator, versus data table gateway) without needing to look at the import statements.
- When importing several classes related to the same _domain_, but different _responsibilities_ within the domain, you will not need to alias (e.g., `AlbumValidator` vs `AlbumTable` vs `AlbumController`).
- By having a suffix, you can group classes by _domain_ instead of _responsibility_:
  ```text
  Album/
      AlbumController.php
      AlbumTable.php
      AlbumValidator.php
  ```

As others have noted, you can achieve some of the same effects by using aliasing when importing classes.

Ultimately, the choice of how you organize the code is up to you and your team. Our goals in creating tutorials are to make clear what class does what, and we have chosen suffixing generally to meet that goal.

**Comment by WinterSilence** [comment]
@weierophinney  pls, add this at begin tutorials, because `namespace Foo\Controller; class Album ..` more readable and shorten than this way.

> By having a suffix, you can group classes by domain instead of responsibility: 

yes, but i cant see this in tutorials

> Our goals in creating tutorials are to make clear what class does what, and we have chosen suffixing generally to meet that goal.

its not only tutorial practice

**Comment by WinterSilence** [comment]
i try say: make tutorial more transparent for beginners. traditions are good, but without explanation they only lead to copying without understanding the meaning.
