### ISSUE TITLE
Same as  zend2

### ISSUE THREAD

**Issue by gurubaksh** [zendframework/tutorials#40]
No tutorial available for zend3 so I can use new feature of zend3. If there is how will come to know

**Comment by divix1988** [comment]
Here is a tutorial of Zend 3 which I've been posted by one of Zend members: https://docs.zendframework.com/tutorials/getting-started/overview/ 

It isn't perfect and in fact current version of Zend 3 is also bad for begginners (pure PHP errors instead of some clean error messages saying that service manager isn't set right and so on..).

**Comment by froschdesign** [comment]
@divix1988 and @gurubaksh 
When you have finished the first tutorial, then got to the "[In-Depth tutorial](https://docs.zendframework.com/tutorials/in-depth-guide/first-module/)".

"[Zend\Expressive](https://docs.zendframework.com/zend-expressive/)" is also a good start for beginners.

Btw. There is no "Zend 1", "Zend 2" or "Zend 3". It is "Zend Framework" or "ZF" (1, 2, 3) 😉 

@divix1988 
Please do not add your problem to every of your post. Thanks!

**Comment by divix1988** [comment]
@froschdesign believe it or not people are already saying Zend 1, 2, 3 when they speak and write (it's more continent, even if it's not 100% correct). And also I am not "adding my problems" I just made an opinion about Zend 3  (yes I've said it) error handling for new-starters. You can take it as a "be aware of" thing if you are starting at new Zend.

Instead of stating: "do not criticise Zend 3" you should think about why people like me post answers like these, there should be always a room for criticism and constructive opinions, especially with new software.

**Comment by froschdesign** [comment]
@divix1988 

>  believe it or not people are already saying Zend 1, 2, 3

Don't forget to look on the smiley!

> "do not criticise Zend 3"

**I never said that!**

Open a separate issue and all is fine.
Adding this problem to a different topic is useless. Open a new bug report for each issue and effective editing is possible.
This helps everyone, because it increase the quality of the documentation, tutorials, code and error messages.

**Comment by divix1988** [comment]
@froschdesign Good point, thanks.

**Comment by froschdesign** [comment]
@gurubaksh 
If you miss some concrete tutorials for ZF3, please open a new issue.
