### ISSUE TITLE
2.4.10 download broken

### ISSUE THREAD

**Issue by glensc** [zendframework/tutorials#70]
as did not find any component to report generic issues, reported to "Default" project
https://framework.zend.com/participate/contributor-guide

the problem:
on download page https://framework.zend.com/downloads/archives

2.4.10 tar.gz link is broken, instead of serving the tarball it shows composer html page
https://packages.zendframework.com/releases/ZendFramework-2.4.10/ZendFramework-2.4.10.tgz

![image](https://cloud.githubusercontent.com/assets/199095/21933421/07349bcc-d9ae-11e6-9424-f1ddba5ebee5.png)

**Comment by froschdesign** [comment]
@weierophinney 
This is still an issue! Can you look at this?

**Comment by weierophinney** [comment]
It does appear to be broken, and, interestingly, I cannot find any build artifacts for that particular release on the server.

Interestingly, we *have* released 2.4.11 since then, so an update should get that version; can you update to that? It contains the latest security fixes, so we'd recommend that version over 2.4.10 regardless. I'm not sure it makes sense for us to re-build the 2.4.10 distribution with a newer one already released supplanting it.
