### ISSUE TITLE
Zend Framework Fatal error:Fatal error: Call to a member function getModuleName() on a non-object in D:\wamp\www\local.api2.voot.com\application\libraries\Zend\Controller\Action\Helper\ViewRenderer.php 

### ISSUE THREAD

**Issue by akashgangrade** [zendframework/tutorials#82]
I am using Zend framework on my project. I have one controller named IndexController.php and other PlayBackController.php. 
I want to call a method of IndexController in playBackController. I have created an object of IndexController but I am getting the error : Fatal error: Call to a member function getModuleName() on a non-object in D:\wamp\www\local.api2.voot.com\application\libraries\Zend\Controller\Action\Helper\ViewRenderer.php .

Is there any way to use the function of IndexController in Zend????

**Comment by jcaillot** [comment]
I might be wrong but it seems like your doing it the wrong way. Any procedure that's shared thru many controllers should be created as a service. This would keep your controllers as lean as possible. Should one really execute a controller action form somewhere else : first check your architecture as it might begin to fissure, then check the action helper. Please prefer SOF or any resource rather than this github to ask for help.

**Comment by akashgangrade** [comment]
Thanks for the answer jcaillot!!
The controllers are created in Services folders. But the problem is I am not able to call one controller to other here in Zend. I am trying to extend the controller classes but that won't work here.

**Comment by weierophinney** [comment]
@akashgangrade I've not got nearly enough information here to go on. I need to see the definitions for each of your `IndexController` and `PlayBackController` (just the constructors, and the specific action methods in question); additionally, a full stack trace from the generated exception message would help a ton. All of this information is necessary, because there are a number of causes for that particular exception message; without more information, any feedback I give will just be guesswork.

Thanks!

**Comment by froschdesign** [comment]
Closing due inactivity.
